# treesitter =================================

# シンタックスハイライト
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
# hooks_file = '~/dotfiles/vim/plugin-configs/lua/nvim-treesitter.lua'
# lua_source = '''
#     require('config.nvim-treesitter')
# '''

# カッコハイライト
[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
on_source = [
    'nvim-treesitter/nvim-treesitter',
]
# lua_add = '''
#     require('nvim-treesitter.configs')
# '''
# hooks_file = '~/dotfiles/vim/plugin-configs/lua/nvim-treesitter.lua'

# タグ自動クローズ
[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_source = [
    'nvim-treesitter/nvim-treesitter',
]
lua_source = '''
    require('config.nvim-treesitter')
'''

# コンテクストコメント
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
on_source = [
    'nvim-treesitter/nvim-treesitter',
]
# lua_source = '''
#     require('nvim-treesitter.configs').setup {}
# '''

