# treesitter =================================

# シンタックスハイライト
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
# lua_source = '''
#     require('config.nvim-treesitter')
# '''

# カッコハイライト
[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
depends = [
    'nvim-treesitter/nvim-treesitter',
]
# lua_add = '''
#     require('nvim-treesitter.configs')
# '''
hooks_file = '~/dotfiles/vim/plugin-configs/lua/nvim-treesitter.lua'

# タグ自動クローズ
[[plugins]]
repo = 'windwp/nvim-ts-autotag'
depends = [
    'nvim-treesitter/nvim-treesitter',
]
# lua_source = '''
#     require('config.nvim-treesitter')
# '''

# コンテクストコメント
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
depends = [
    'nvim-treesitter/nvim-treesitter',
]
# lua_source = '''
#     require('nvim-treesitter.configs').setup {}
# '''

