# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = [
    'mason-lspconfig.nvim'
    'rrethy/vim-illuminate',
    # 'read-or-create-venv.vim',
]
hooks_file = '~/dotfiles/vim/plugin-configs/lua/lsp.lua'
# lua_add = '''
#     require('config.lsp')
# '''

# LSP設定
[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'mason.nvim'

# フォーマッター・リンター
# [[plugins]]
# repo = 'jose-elias-alvarez/null-ls.nvim'
# on_source = 'mason.nvim'
# hooks_source = '~/dotfiles/vim/plugin-configs/lua/null-ls.lua'
# lua_source = '''
#     require('config.null-ls')
# '''

[[plugins]]
repo = 'nvimtools/none-ls.nvim'
on_source = 'mason.nvim'
hooks_fils = '~/dotfiles/vim/plugin-configs/lua/none-ls.lua'

# null-ls設定
repo = 'jayp0521/mason-null-ls.nvim'
on_source = [
    'mason.nvim',
    'none-ls',
]

[[plugins]]
repo = 'folke/neodev.nvim'
on_source = 'nvim-lspconfig'
