# プラグインマネージャー

[[plugins]]
if = 0
repo = 'Shougo/dein.vim'

[[plugins]]
if = 0
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
if = 0
repo = 'osyo-manga/vim-precious'
depends = [
    'context_filetype.vim',
]

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# GithubCopilot

[[plugins]]
repo = 'github/copilot.vim'
on_cmd = 'Copilot'
on_event = [
    'InsertEnter',
]

# パッケージマネージャー

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = [
    'mason-lspconfig.nvim',
    'nvim-lspconfig',
]

# 通知

[[plugins]]
repo = 'rcarriga/nvim-notify'
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/nvim-notify.lua'

# 自動インデント検出

[[plugins]]
repo = 'Darazaki/indent-o-matic'
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/indent-o-matic.lua'

# FixCursorHold

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/FixCursorHold.lua'

# アイコン

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

# バッファライン

[[plugins]]
repo = 'akinsho/bufferline.nvim'
rev = '*'
depends = [
    'nvim-tree/nvim-web-devicons',
]
lua_add = '''
    vim.opt.termguicolors = true
    require('bufferline').setup{}
'''

# ステータスライン

[[plugins]]
if = 0
repo = 'vim-airline/vim-airline'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/vim-airline.vim'

[[plugins]]
if = 0
repo = 'vim-airline/vim-airline-themes'
on_source = [
    'vim-airline',
]

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = [
    'nvim-tree/nvim-web-devicons',
]
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/lualine.lua'

# FZF

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/fzf.vim'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'
on_source = [
    'fzf',
]

# Autopairs

[[plugins]]
repo = 'windwp/nvim-autopairs'
lua_add = '''
    require('nvim-autopairs').setup{}
'''

# カラースキーマ

[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_source = '''
    " colorscheme codedark
    " au MyAutoCmd VimEnter * nested colorscheme codedark
    autocmd VimEnter * ++nested colorscheme codedark
'''

[[plugins]]
repo = 'WhoIsSethDaniel/mason-tool-installer.nvim'
on_source = [
    'mason.nvim',
]

[[plugins]]
repo = 'SmiteshP/nvim-navic'
on_source = [
    'nvim-lspconfig',
]
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/nvim-navic.lua'

[[plugins]]
repo = 'utilyre/barbecue.nvim'
depends = [
    'nvim-navic',
    'nvim-web-devicons',
]
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/barbecue.lua'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'numToStr/Comment.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'SmiteshP/nvim-navbuddy'
on_source = [
    'nvim-lspconfig',
    'nvim-navic',
    'nui.nvim',
    'Comment.nvim',
    'telescope.nvim',
]

[[plugins]]
repo = 'folke/trouble.nvim'
on_source = [
    'kyazdani42/nvim-web-devicons',
]
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/trouble.lua'

# インデント

[[plugins]]
repo = 'Yggdroot/indentLine'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/indentLine.vim'

# GIT系 ----------------------

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/vim-gitgutter.vim'

# vim rooter
[[plugins]]
repo = 'airblade/vim-rooter'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/vim-rooter.vim'

[[plugins]]
repo = 'rickhowe/diffchar.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'APZelos/blamer.nvim'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/blamer.vim'

[[plugins]]
if = 0
repo = 'gelguy/wilder.nvim'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/wilder.vim'

# fern.vim

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

# reword

[[plugins]]
repo = 'lambdalisue/reword.vim'

# rainvow_csv

[[plugins]]
repo = 'mechatroner/rainbow_csv'

# lazygit.vim

[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/lazygit.vim'

# pastefix

[[plugins]]
repo = 'lambdalisue/pastefix.vim'

# denops

[[plugins]]
repo = 'vim-denops/denops.vim'

# deoppet
[[plugins]]
if = 0
repo = 'Shougo/deoppet.nvim'
on_source = [
    'yohi/install-pip-package.nvim',
]
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/deoppet.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/plenary.lua'

[[plugins]]
repo = 'MunifTanjim/prettier.nvim'

# ADD ======================================

[[plugins]]
repo = 'Shougo/neomru.vim'

# Filer

[[plugins]]
repo = 'scrooloose/nerdtree'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/nerdtree.vim'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_event = [
    'LspAttach',
]
lua_add = '''
    require('fidget').setup{}
'''

[[plugins]]
repo = 'mhartington/oceanic-next'

# Add surrounding character
[[plugins]]
repo = 'tpope/vim-surround'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/vim-surround.vim'

# Replacement preview
[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'skanehira/denops-translate.vim'
depends = [
    'denops.vim',
]
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/denops-translate.vim'

[[plugins]]
repo = 'elzr/vim-json'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/vim-json.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = 'npm ci'
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/coc.lua'

[[plugins]]
repo = 'yaegassy/coc-mypy'
build = 'yarn install --frozen-lockfile'

# 自作
[[plugins]]
if = 0
repo = '~/dotfiles/vim/local_plugins/set-docker-compose-env.nvim'
lua_source = '''
    require('set-docker-compose-env').setup()
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
hooks_file = '~/dotfiles/vim/dpp/hooks/rc/ddu.vim'

[[plugins]]
repo = 'jackMort/ChatGPT.nvim'
on_event = [
    'VeryLazy',
]
depends = [
    'MunifTanjim/nui.nvim',
    'nvim-lua/plenary.nvim',
    'folke/trouble.nvim',
    'nvim-telescope/telescope.nvim',
]
lua_add = '''
    vim.fn.setenv('OPENAI_API_KEY', 'dummy')
    vim.fn.setenv('OPENAI_API_HOST', 'http://localhost:32768')
    require('chatgpt').setup({
        openai_params = {
          model = 'bedrock/anthropic.claude-3-sonnet-20240229-v1:0',
        },
        openai_edit_params = {
          model = 'bedrock/anthropic.claude-3-sonnet-20240229-v1:0',
        },
        actions_paths = {
            '~/dotfiles/vim/chatgpt-nvim-actions.json'
        },
})
'''
