######################################################################
# LAZY
######################################################################


[[plugins]]  # to Lazy
if = 0
repo   = 'rhysd/git-messenger.vim'
# on_cmd = 'GitMessenger'
# on_map = '<Plug>(git-messenger)'
# hook_add = ''' "{{{
#   -- let g:git_messenger_no_default_mappings = v:true
#   -- nnoremap <A-b> :GitMessenger<CR>
# "}}} '''


[[plugins]]
repo = 'dense-analysis/ale'
hooks_file = '~/dotfiles/vim/plugin-configs/rc/ale.vim'
