# treesitter =================================

# シンタックスハイライト
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hooks_file = '~/dotfiles/vim/dpp/hooks/lua/nvim-treesitter.lua'
# rev = 'main'
# lua_source = '''
#     require('config.nvim-treesitter')
# '''

# カッコハイライト
[[plugins]]
repo = 'hiphish/rainbow-delimiters.nvim'
on_source = [
    'nvim-treesitter/nvim-treesitter',
]

# タグ自動クローズ
[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_source = [
    'nvim-treesitter/nvim-treesitter',
]

# コンテクストコメント
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
on_source = [
    'nvim-treesitter/nvim-treesitter',
]
